[project]
name = 'taskfi-clarity'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.taskfi-utils]
path = 'contracts/taskfi-utils.clar'
clarity_version = 3
epoch = 3.1

[contracts.taskfi-admin]
path = 'contracts/taskfi-admin.clar'
clarity_version = 3
epoch = 3.1
depends_on = ['taskfi-utils']

[contracts.taskfi-governance]
path = 'contracts/taskfi-governance.clar'
clarity_version = 3
epoch = 3.1
depends_on = ['taskfi-utils', 'taskfi-admin']

[contracts.taskfi-reputation]
path = 'contracts/taskfi-reputation.clar'
clarity_version = 3
epoch = 3.1
depends_on = ['taskfi-utils', 'taskfi-admin']

[contracts.taskfi-dispute]
path = 'contracts/taskfi-dispute.clar'
clarity_version = 3
epoch = 3.1
depends_on = ['taskfi-utils', 'taskfi-admin', 'taskfi-reputation']

[contracts.taskfi-staking]
path = 'contracts/taskfi-staking.clar'
clarity_version = 3
epoch = 3.1
depends_on = ['taskfi-utils', 'taskfi-admin']

[contracts.taskfi-escrow]
path = 'contracts/taskfi-escrow.clar'
clarity_version = 3
epoch = 3.1
depends_on = ['taskfi-utils', 'taskfi-admin']

[contracts.taskfi-core]
path = 'contracts/taskfi-core.clar'
clarity_version = 3
epoch = 3.1
depends_on = ['taskfi-utils', 'taskfi-admin', 'taskfi-reputation', 'taskfi-dispute', 'taskfi-staking', 'taskfi-escrow', 'taskfi-governance']
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
