[project]
name = 'taskfi-clarity'
description = 'TaskFi - Decentralized task marketplace on Stacks'
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.taskfi-core]
path = 'contracts/taskfi-core.clar'
clarity_version = 3
epoch = 3.1

[contracts.taskfi-escrow]
path = 'contracts/taskfi-escrow.clar'
clarity_version = 3
epoch = 3.1

[contracts.taskfi-reputation]
path = 'contracts/taskfi-reputation.clar'
clarity_version = 3
epoch = 3.1

[contracts.taskfi-staking]
path = 'contracts/taskfi-staking.clar'
clarity_version = 3
epoch = 3.1

[contracts.taskfi-dispute]
path = 'contracts/taskfi-dispute.clar'
clarity_version = 3
epoch = 3.1

[contracts.taskfi-admin]
path = 'contracts/taskfi-admin.clar'
clarity_version = 3
epoch = 3.1

[contracts.taskfi-utils]
path = 'contracts/taskfi-utils.clar'
clarity_version = 3
epoch = 3.1

[contracts.taskfi-governance]
path = 'contracts/taskfi-governance.clar'
clarity_version = 3
epoch = 3.1
depends_on = ['taskfi-reputation']

[contracts.analytics]
path = 'contracts/analytics.clar'
clarity_version = 3
epoch = 3.1

[contracts.governance]
path = 'contracts/governance.clar'
clarity_version = 3
epoch = 3.1

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
