[project]
name = 'taskfi-clarity'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.taskfi-core]
path = 'contracts/taskfi-core.clar'
clarity_version = 3
epoch = 3.1

[contracts.taskfi-escrow]
path = 'contracts/taskfi-escrow.clar'
clarity_version = 3
epoch = 3.1

[contracts.taskfi-staking]
path = 'contracts/taskfi-staking.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
